# Generated by Django 4.1.3 on 2023-01-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Academic Division Name')),
                ('acad_div_type', models.CharField(max_length=256, verbose_name='Academic Division Type')),
                ('web', models.URLField(verbose_name='Website address')),
            ],
        ),
        migrations.CreateModel(
            name='ResExUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=128, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Lab Name')),
                ('faculty', models.CharField(max_length=256, verbose_name='Faculty associated')),
                ('contact', models.CharField(max_length=256, verbose_name='Contact number')),
                ('description', models.TextField(blank=True)),
                ('web', models.URLField(verbose_name='Website address')),
                ('email_address', models.EmailField(max_length=128, verbose_name='Email Address')),
                ('academic_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labs.academic_division')),
                ('associated_users', models.ManyToManyField(blank=True, to='labs.resexuser')),
            ],
        ),
    ]
