# Generated by Django 4.1.3 on 2023-01-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_academic_division_acad_div_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='contact',
            field=models.CharField(blank=True, max_length=256, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='email_address',
            field=models.EmailField(blank=True, max_length=128, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website address'),
        ),
    ]
