# Generated by Django 4.1.3 on 2023-01-05 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0004_lab_poc_manager_alter_lab_academic_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='poc_manager',
        ),
        migrations.AddField(
            model_name='lab',
            name='poc_manager',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
