# Generated by Django 4.1.3 on 2023-01-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_remove_lab_poc_manager_lab_poc_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='faculty',
            field=models.CharField(blank=True, max_length=256, verbose_name='Faculty associated'),
        ),
    ]
