# Generated by Django 4.1.3 on 2023-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_academic_division_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_division',
            name='acad_div_type',
            field=models.CharField(choices=[('Department', 'Department'), ('School', 'School'), ('Interdisciplinary Program', 'Interdisciplinary Program'), ('Centre', 'Centre')], default='Department', max_length=28, verbose_name='Academic Division Type'),
        ),
    ]
