# Generated by Django 4.1.3 on 2023-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_alter_academic_division_acad_div_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='research_equipment',
            field=models.TextField(blank=True),
        ),
    ]
