# Generated by Django 4.1.3 on 2023-02-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_alter_lab_poc_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
