# Generated by Django 4.1.3 on 2023-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
